# 数组类型

In [1]:
from numpy import *

## 复数数组
产生一个复数数组：

In [3]:
a = array([1 + 1j, 2, 3, 4])

In [5]:
# python 会自动判断数组类型
a.dtype

dtype('complex128')

对于附属我们可以查看他的实部和虚部

In [7]:
a.real

array([1., 2., 3., 4.])

In [8]:
a.imag

array([1., 0., 0., 0.])

还可以设置他们的值

In [9]:
a.imag = [1, 2, 3, 4]

In [11]:
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

查看复共轭：

In [12]:
a.conj()

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

事实上，这些属性方法可以用在浮点数或者整数数组上：



In [13]:
a = array([0.,1,2,3])
a.dtype

dtype('float64')

In [14]:
a.real

array([0., 1., 2., 3.])

In [15]:
a.imag

array([0., 0., 0., 0.])

In [16]:
a.conj()

array([0., 1., 2., 3.])

但这里，虚部是只读的，并不能修改它的值：

In [18]:
# 会报错
a.imag = [1,2,3,4]

TypeError: array does not have imaginary part to set

## 指定数组类型
之前已经知道，构建数组的时候，数组会根据传入的内容自动判断类型：

In [20]:
a = array([0, 1.0, 2, 3])

对于浮点数，默认为双精度

In [21]:
a.dtype

dtype('float64')

查看所用的字节（8byte*4）

In [23]:
a.nbytes

32

当然我们也可以在构建的时候制定类型

In [24]:
a = array([0, 1.0, 2 ,3],
         dtype=float32)

此时类型为单精度浮点数

In [25]:
a.dtype

dtype('float32')

查看所用字节（4byte * 4）：

In [26]:
a.nbytes

16

除此之外，还可以指定的有无符号，例如无符号整数。

In [27]:
a = array([0, 1, 2, 3],
         dtype=uint8)
a.dtype

dtype('uint8')

```uint8```只是用一个字节，表示0到255的整数

还可以从二进制数据中读取。

先写入二进制数据

In [37]:
a = array([102,111,212],
         dtype=uint8)
a.tofile('foo.dat')

从数据中读入，要指定类型：

In [38]:
b = frombuffer('foo', 
               dtype=uint8)
b

TypeError: a bytes-like object is required, not 'str'

清理数据文件：

In [39]:
import os
os.remove('foo.dat')


0-255 的数字可以表示ASCⅡ码，我们可以用 ord 函数来查看字符的ASCⅡ码值：



In [40]:
ord('f')

102

In [41]:
ord('s')

115

## Numpy 类型

基本类型|可用的Numpy类型|备注
---|---|---
布尔型|bool|占1个字节
整型|int8, int16, int32, int64, int128, int|int 跟C语言中的 long 一样大
无符号整型|uint8, uint16, uint32, uint64, uint128, uint|uint 跟C语言中的 unsigned long 一样大
浮点数|float16, float32, float64, float, longfloat|默认为双精度 float64 ，longfloat 精度大小与系统有关
复数|complex64, complex128, complex, longcomplex|默认为 complex128 ，即实部虚部都为双精度
字符串|string, unicode|可以使用 dtype=S4 表示一个4字节字符串的数组
对象|object|数组中可以使用任意值
Records|void
时间|datetime64, timedelta64

任意类型的数组：

In [44]:
a = array([1,1.2,'hello', [10,20,30]], 
          dtype=object)

In [45]:
# 乘法
a*2

array([2, 2.4, 'hellohello', list([10, 20, 30, 10, 20, 30])], dtype=object)

## 类型转换
转换数组的类型

In [46]:
a = array([1.5, -3],
         dtype=float32)
a

array([ 1.5, -3. ], dtype=float32)

### asarray函数
使用```asarray```函数

In [48]:
asarray(a, dtype=float64)

array([ 1.5, -3. ])

In [49]:
asarray(a, dtype=uint8)

array([  1, 253], dtype=uint8)

注意：asarray不会修改原来数组的值

In [51]:
a

array([ 1.5, -3. ], dtype=float32)

但当类型相同的时候，asarray 并不会产生新的对象，而是使用同一个引用：

In [53]:
b = asarray(a, dtype=float32)

In [54]:
b is a

True

这么做的好处在与，asarray 不仅可以作用于数组，还可以将其他类型转化为数组。

有些时候为了保证我们的输入值是数组，我们需要将其使用 asarray 转化，当它已经是数组的时候，并不会产生新的对象，这样保证了效率。

In [55]:
asarray([1,2,3,4])

array([1, 2, 3, 4])

## astype 方法
astype 方法返回一个新数组：

In [58]:
a.astype(float64)

array([ 1.5, -3. ])

In [59]:
a.astype(uint8)

array([  1, 253], dtype=uint8)

astype也不会改变原来数组的值：

In [61]:
a

array([ 1.5, -3. ], dtype=float32)

另外，astype 总是返回原来数组的一份复制，即使转换的类型是相同的：

In [63]:
b = a.astype(float32)
print (a)
print (b)

[ 1.5 -3. ]
[ 1.5 -3. ]


In [64]:
a is b

False

## view方法

In [65]:
a = array((1,2,3,4), dtype=int32)
a

array([1, 2, 3, 4], dtype=int32)

view 会将 a 在内存中的表示看成是 uint8 进行解析：



In [66]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)